// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class DescriptionImage
    {
        public string ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImageLink { get; set; }
        public string StoreId { get; set; }

        public virtual Store Store { get; set; }
    }
}