// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Discount
    {
        public Discount()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public string DiscountId { get; set; }
        public string DiscountName { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public double? PercentDiscount { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}