// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class District
    {
        public District()
        {
            Products = new HashSet<Product>();
            UserAddresses = new HashSet<UserAddress>();
            Wards = new HashSet<Ward>();
        }

        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int CityId { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<Ward> Wards { get; set; }
    }
}