// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Invoice
    {
        public string InvoiceId { get; set; }
        public string InvoiceName { get; set; }
        public DateTime? AccountingDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? Amount { get; set; }
        public int? TotalAmount { get; set; }
        public string VoucherId { get; set; }
        public int? VoucherType { get; set; }
        public double? VoucherValue { get; set; }
        public string UserId { get; set; }
        public string OrderId { get; set; }
        public string StoreId { get; set; }

        public virtual Order Order { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}