// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Order
    {
        public Order()
        {
            Invoices = new HashSet<Invoice>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        public string OrderId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? Amount { get; set; }
        public int? TotalAmount { get; set; }
        public int Status { get; set; }
        public string CustomerId { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public string Notes { get; set; }
        public string ShipAddress { get; set; }
        public int? DiscountAmount { get; set; }
        public string VoucherId { get; set; }
        public string VoucherType { get; set; }
        public double? VoucherValue { get; set; }
        public int ShippingStatus { get; set; }
        public string InvoiceId { get; set; }
        public DateTime? EstimatedShippingDate { get; set; }
        public int? Shippingfee { get; set; }

        public virtual User Customer { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}