// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class OrderDetail
    {
        public string OrderDetailId { get; set; }
        public int Price { get; set; }
        public double? Quantity { get; set; }
        public string UnitId { get; set; }
        public string UnitName { get; set; }
        public string DiscountId { get; set; }
        public double? DiscountValue { get; set; }
        public string ProductId { get; set; }
        public string OrderId { get; set; }
        public int? TotalAmount { get; set; }

        public virtual Discount Discount { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}