// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Product
    {
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
            ProductImages = new HashSet<ProductImage>();
            UserReportProducts = new HashSet<UserReportProduct>();
        }

        public string ProductId { get; set; }
        public string ProductCategoryId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string SubDescription { get; set; }
        public int Price { get; set; }
        public string VideoLink { get; set; }
        public string StoreId { get; set; }
        public string SearchString { get; set; }
        public int? QuantitySold { get; set; }
        public double? Rating { get; set; }
        public bool? IsDiscountPercent { get; set; }
        public double? DiscountAmount { get; set; }

        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<UserReportProduct> UserReportProducts { get; set; }
    }
}