// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Rating
    {
        public string RatingId { get; set; }
        public string Comment { get; set; }
        public int Star { get; set; }
        public string ProductId { get; set; }
        public string CustomerId { get; set; }

        public virtual User Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}