// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class ReportType
    {
        public ReportType()
        {
            UserReportProducts = new HashSet<UserReportProduct>();
        }

        public int ReportType1 { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserReportProduct> UserReportProducts { get; set; }
    }
}