// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Store
    {
        public Store()
        {
            DescriptionImages = new HashSet<DescriptionImage>();
            Products = new HashSet<Product>();
            UserReportProducts = new HashSet<UserReportProduct>();
        }

        public string StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreLogo { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public int WardId { get; set; }
        public string ShortAddress { get; set; }
        public string FullAddress { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public int? Wallet { get; set; }
        public bool? IsBaned { get; set; }

        public virtual ICollection<DescriptionImage> DescriptionImages { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UserReportProduct> UserReportProducts { get; set; }
    }
}