// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Unit
    {
        public Unit()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public string UnitId { get; set; }
        public string UnitName { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}