// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class UserReportProduct
    {
        public string ReportId { get; set; }
        public string UserId { get; set; }
        public string ProductId { get; set; }
        public string StoreId { get; set; }
        public int ReportType { get; set; }
        public string ReportTypeName { get; set; }
        public string Notes { get; set; }

        public virtual Product Product { get; set; }
        public virtual ReportType ReportTypeNavigation { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}