// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class User
    {
        public User()
        {
            Invoices = new HashSet<Invoice>();
            Orders = new HashSet<Order>();
            UserAddresses = new HashSet<UserAddress>();
            UserReportProducts = new HashSet<UserReportProduct>();
        }

        public string UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Token { get; set; }
        public DateTime CreatedAt { get; set; }
        public int RoleId { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ShipAddressId { get; set; }
        public string ShipAddress { get; set; }
        public bool? IsBaned { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<UserReportProduct> UserReportProducts { get; set; }
    }
}