// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class UserAddress
    {
        public string AddressId { get; set; }
        public string FullAddress { get; set; }
        public string ShortAddress { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public int WardId { get; set; }
        public string UserId { get; set; }

        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual User User { get; set; }
        public virtual Ward Ward { get; set; }
    }
}