// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sv.Sale.DBModels
{
    public partial class Ward
    {
        public Ward()
        {
            UserAddresses = new HashSet<UserAddress>();
        }

        public int WardId { get; set; }
        public string WardName { get; set; }
        public int DistrictId { get; set; }

        public virtual District District { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}